# Generated by Django 4.1.5 on 2023-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='top3_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='top3_genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
